# Generated by Django 3.2.16 on 2023-06-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_address', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=20)),
                ('acres', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=100)),
                ('curr_zoning', models.CharField(max_length=50)),
                ('prop_zoning', models.CharField(max_length=50)),
            ],
        ),
    ]
