# Generated by Django 3.2.16 on 2023-06-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newBernTOD', '0004_auto_20230603_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparcel',
            name='acres',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalparcel',
            name='pin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='acres',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='pin',
            field=models.CharField(max_length=50),
        ),
    ]
