# Generated by Django 3.2.16 on 2023-06-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newBernTOD', '0005_auto_20230603_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparcel',
            name='acres',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalparcel',
            name='curr_zoning',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalparcel',
            name='owner',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalparcel',
            name='pin',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalparcel',
            name='prop_zoning',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='acres',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='curr_zoning',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='owner',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='pin',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='prop_zoning',
            field=models.CharField(max_length=200),
        ),
    ]
