# Generated by Django 3.2.16 on 2023-06-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newBernTOD', '0006_auto_20230603_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparcel',
            name='property_address',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='property_address',
            field=models.CharField(max_length=400),
        ),
    ]
