# Generated by Django 3.2.16 on 2023-06-24 11:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newBernTOD', '0010_auto_20230607_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlay',
            name='EFF_DATE',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overlay',
            name='OBJECTID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overlay',
            name='OLAY_NAME',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='overlay',
            name='ORDINANCE',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='overlay',
            name='ZONE_CASE',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='overlay',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
