# Generated by Django 3.2.16 on 2023-06-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newBernTOD', '0011_auto_20230624_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlay',
            name='OVERLAY',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
