# Generated by Django 3.2.16 on 2023-06-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newBernTOD', '0013_overlay2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Overlay2',
        ),
    ]
