# Generated by Django 3.2.16 on 2023-06-26 14:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newBernTOD', '0014_delete_overlay2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overlay2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OLAY_NAME', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('OVERLAY', models.CharField(blank=True, max_length=250, null=True)),
                ('OBJECTID', models.IntegerField(blank=True, null=True)),
                ('ZONE_CASE', models.CharField(blank=True, max_length=250, null=True)),
                ('ORDINANCE', models.CharField(blank=True, max_length=250, null=True)),
                ('EFF_DATE', models.BigIntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('parcels', models.ManyToManyField(blank=True, default=None, to='newBernTOD.Parcel')),
            ],
        ),
    ]
