# Generated by Django 3.2.16 on 2023-06-26 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newBernTOD', '0016_auto_20230626_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overlay',
            old_name='OLAY_NAME',
            new_name='olay_name',
        ),
        migrations.RenameField(
            model_name='overlay',
            old_name='OVERLAY',
            new_name='overlay',
        ),
    ]
