# Generated by Django 3.2.16 on 2023-06-27 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newBernTOD', '0018_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hod',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hod',
            name='parcels',
            field=models.ManyToManyField(blank=True, default=None, to='newBernTOD.Parcel'),
        ),
    ]
