# Generated by Django 4.1.8 on 2023-07-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newBernTOD", "0019_auto_20230626_2011"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalparcel",
            name="design_style_decode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalparcel",
            name="designstyl",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalparcel",
            name="sale_date",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalparcel",
            name="site",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalparcel",
            name="totstructs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalparcel",
            name="totunits",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalparcel",
            name="type_and_use",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalparcel",
            name="type_use_decode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalparcel",
            name="units",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="design_style_decode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="designstyl",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="sale_date",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="site",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="totstructs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="totunits",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="type_and_use",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="type_use_decode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="units",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
