# Generated by Django 4.1.8 on 2023-07-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newBernTOD", "0020_historicalparcel_design_style_decode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalparcel",
            name="sale_date",
            field=models.IntegerField(blank=True, null=True, verbose_name="Sale Date"),
        ),
        migrations.AlterField(
            model_name="historicalparcel",
            name="totsalprice",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=11,
                null=True,
                verbose_name="Sale Price",
            ),
        ),
        migrations.AlterField(
            model_name="historicalparcel",
            name="totstructs",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Total Structures"
            ),
        ),
        migrations.AlterField(
            model_name="historicalparcel",
            name="totunits",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Total Units"
            ),
        ),
        migrations.AlterField(
            model_name="historicalparcel",
            name="units",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=11, null=True
            ),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="sale_date",
            field=models.IntegerField(blank=True, null=True, verbose_name="Sale Date"),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="totsalprice",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=11,
                null=True,
                verbose_name="Sale Price",
            ),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="totstructs",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Total Structures"
            ),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="totunits",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Total Units"
            ),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="units",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=11, null=True
            ),
        ),
    ]
