# Generated by Django 4.1.8 on 2023-07-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newBernTOD", "0021_alter_historicalparcel_sale_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalparcel",
            name="site",
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="site",
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
