# Generated by Django 4.1.8 on 2023-07-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newBernTOD", "0022_alter_historicalparcel_site_alter_parcel_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalparcel",
            name="site",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="site",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
