# Generated by Django 4.1.8 on 2023-07-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newBernTOD", "0023_alter_historicalparcel_site_alter_parcel_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalparcel",
            name="sale_date",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Sale Date"
            ),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="sale_date",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Sale Date"
            ),
        ),
    ]
