# Generated by Django 4.1.8 on 2023-07-17 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newBernTOD", "0024_alter_historicalparcel_sale_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parcel", options={"ordering": ["modified_date"]},
        ),
    ]
