# Generated by Django 4.1.8 on 2023-07-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newBernTOD", "0025_alter_parcel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalparcel",
            name="acres",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="historicalparcel",
            name="curr_zoning",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="historicalparcel",
            name="owner",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="historicalparcel",
            name="prop_zoning",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="acres",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="curr_zoning",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="owner",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="prop_zoning",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
