# Generated by Django 4.1.8 on 2023-07-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newBernTOD", "0026_alter_historicalparcel_acres_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalparcel",
            name="defunct_pin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="parcel",
            name="defunct_pin",
            field=models.BooleanField(default=False),
        ),
    ]
