# Generated by Django 4.1.10 on 2023-09-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newBernTOD", "0027_historicalparcel_defunct_pin_parcel_defunct_pin"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalparcel",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="parcel",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
