# Generated by Django 4.1.10 on 2023-09-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newBernTOD", "0028_historicalparcel_is_active_parcel_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalparcel",
            name="objectid",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parcel",
            name="objectid",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
