# Generated by Django 4.1.10 on 2023-09-17 13:35

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Parcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_address", models.CharField(max_length=400)),
                ("objectid", models.IntegerField()),
                ("pin", models.CharField(max_length=200)),
                ("defunct_pin", models.BooleanField(default=False)),
                ("acres", models.CharField(blank=True, max_length=200, null=True)),
                ("owner", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "curr_zoning",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "prop_zoning",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PolygonField(
                        null=True, srid=4326
                    ),
                ),
                ("reid", models.CharField(blank=True, max_length=20, null=True)),
                ("addr1", models.CharField(blank=True, max_length=100, null=True)),
                ("addr2", models.CharField(blank=True, max_length=100, null=True)),
                ("addr3", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "deed_acres",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=11, null=True
                    ),
                ),
                ("bldg_val", models.IntegerField(blank=True, null=True)),
                ("land_val", models.IntegerField(blank=True, null=True)),
                ("total_value_assd", models.IntegerField(blank=True, null=True)),
                ("propdesc", models.CharField(blank=True, max_length=250, null=True)),
                ("year_built", models.IntegerField(blank=True, null=True)),
                (
                    "totsalprice",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=11,
                        null=True,
                        verbose_name="Sale Price",
                    ),
                ),
                (
                    "sale_date",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Sale Date"
                    ),
                ),
                (
                    "type_and_use",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "type_use_decode",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("designstyl", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "design_style_decode",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "units",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "totstructs",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Structures"
                    ),
                ),
                (
                    "totunits",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Units"
                    ),
                ),
                ("site", models.IntegerField(blank=True, null=True)),
            ],
            options={"ordering": ["modified_date"],},
        ),
        migrations.CreateModel(
            name="HistoricalParcel",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("property_address", models.CharField(max_length=400)),
                ("objectid", models.IntegerField()),
                ("pin", models.CharField(max_length=200)),
                ("defunct_pin", models.BooleanField(default=False)),
                ("acres", models.CharField(blank=True, max_length=200, null=True)),
                ("owner", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "curr_zoning",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "prop_zoning",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_date", models.DateTimeField(blank=True, editable=False)),
                ("modified_date", models.DateTimeField(blank=True, editable=False)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PolygonField(
                        null=True, srid=4326
                    ),
                ),
                ("reid", models.CharField(blank=True, max_length=20, null=True)),
                ("addr1", models.CharField(blank=True, max_length=100, null=True)),
                ("addr2", models.CharField(blank=True, max_length=100, null=True)),
                ("addr3", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "deed_acres",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=11, null=True
                    ),
                ),
                ("bldg_val", models.IntegerField(blank=True, null=True)),
                ("land_val", models.IntegerField(blank=True, null=True)),
                ("total_value_assd", models.IntegerField(blank=True, null=True)),
                ("propdesc", models.CharField(blank=True, max_length=250, null=True)),
                ("year_built", models.IntegerField(blank=True, null=True)),
                (
                    "totsalprice",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=11,
                        null=True,
                        verbose_name="Sale Price",
                    ),
                ),
                (
                    "sale_date",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Sale Date"
                    ),
                ),
                (
                    "type_and_use",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "type_use_decode",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("designstyl", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "design_style_decode",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "units",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "totstructs",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Structures"
                    ),
                ),
                (
                    "totunits",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Units"
                    ),
                ),
                ("site", models.IntegerField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical parcel",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
