# Generated by Django 4.1.8 on 2023-07-15 18:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objectid", models.IntegerField()),
                ("globalid", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "crime_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "crime_description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("crime_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "reported_block_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("reported_date", models.BigIntegerField(blank=True, null=True)),
                ("reported_year", models.IntegerField(blank=True, null=True)),
                ("reported_month", models.IntegerField(blank=True, null=True)),
                ("reported_day", models.IntegerField(blank=True, null=True)),
                ("reported_hour", models.IntegerField(blank=True, null=True)),
                (
                    "reported_dayofwk",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("is_glenwood_south", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RaleighPoliceDistrict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objectid", models.IntegerField()),
                ("district", models.CharField(max_length=3)),
                ("shape_are", models.FloatField()),
                ("shape_len", models.FloatField()),
                ("zoneid", models.IntegerField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrackArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objectid", models.IntegerField()),
                ("short_name", models.CharField(max_length=8)),
                ("long_name", models.CharField(max_length=50)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
    ]
