# Generated by Django 3.2.8 on 2022-06-25 19:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Border',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muni_name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('border_geojson', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('PIN_NUM', models.CharField(max_length=20, null=True)),
                ('ADDR1', models.CharField(max_length=200, null=True)),
                ('PROPDESC', models.CharField(max_length=300, null=True)),
                ('SITE_ADDRESS', models.CharField(max_length=200, null=True)),
                ('YEAR_BUILT', models.IntegerField()),
                ('TYPE_USE_DECODE', models.CharField(max_length=50, null=True)),
                ('CITY', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Decade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decade_name', models.CharField(max_length=20, null=True)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('output_geojson_reduced', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start_year'],
            },
        ),
    ]
