# Generated by Django 3.2.8 on 2022-08-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('output_geojson', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='DEED_ACRES',
            field=models.DecimalField(decimal_places=6, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='LAND_VAL',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='LAND_VAL_per_DEED_ACRES',
            field=models.DecimalField(decimal_places=9, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='YEAR_BUILT',
            field=models.IntegerField(null=True),
        ),
    ]
